### ISSUE TITLE
JVT warning in JetSelector

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#1077]
Hello

I'm seeing the following warning:

JetSelector.TruthSelectorWARNING note: handle CP::JetJvtEfficiency/JVT_eff_tool is user configured. If this is expected, ignore the message. If it is not expected, look into JetSelector::TruthSelector, check documentation, or ask around.
JetSelector.TruthSelec...INFO    Will be using JetJvtEfficiency tool JVT efficiency systematic:
JetSelector.TruthSelec...INFO            Running w/ nominal configuration only!

I'm using JetSelector to select truth jets, this is what I have in my JSON file:

{ "class": "JetSelector",
     "configs": {
      "m_name": "TruthSelector",
      "m_inContainerName": "AntiKt4TruthWZJets",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4TruthWZJets_Signal",
      "m_outputAlgo":  "AntiKt4TruthWZJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
   },

I obviously don't care about JVT for truth jets but since I'm not enabling anything related with JVT I'm surprised (maybe something changed recently, I just checked out from the repo).

Best,
Jona

**Comment by kratsg** [comment]
So what this is saying in [JetSelector](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L271-L277) from [setToolName](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/xAODAnaHelpers/Algorithm.h#L251-L259) is that the tool of type `CP::JetJvtEfficiency` and name `JVT_eff_tool` was already previously configured somewhere else and that the algorithm will be retrieving the previously configured one and the configurations that would be set on it will be ignored. That is, if you are trying to reconfigure the tool, you cannot. You just need to use a different name. Unfortunately, it's not a configurable name right now, but it should be. If you don't care - it's ok for right now. We should probably make it configurable so that two different tools can be made in different JetSelectors instead of them sharing the same one.

Does that make sense? We're just more cautious/explicit about these things now.

**Comment by jbossios** [comment]
Thank you @kratsg for the clarification!
I usually need several JetSelector's instances, but at least so far I only need JVT for one of them, so it's fine for me.
Best,
Jona

**Comment by kratsg** [comment]
Yeah, so they'll all share the same JVT instance for now.. this isn't the worst problem - if you're fine with that, then that's ok. That's generally why it's a warning and not an error.
