### ISSUE TITLE
JVT recommended cut

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#132]
Hi @jdandoy ,

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/data/jetSelect_signal.config#L13

Is this the actual recommendation for Run2?

Marco

**Comment by gfacini** [comment]
Probably not...I might have done this.
7 TeV was 0.5
8 TeV was 0.25
Run II is JVT I believe.

Can you follow up and confirm and / or advise a different default value for this?

**Comment by jdandoy** [comment]
My understanding is JVT is recommended, but JVF is not.  That config file
has the current JVT recommendation.

Jeff

**Comment by mmilesi** [comment]
Hi @gfacini , @jdandoy 

I am aware that JVT is now recommended and JVF deprecated ;-)

My question was on the actual value for the JVT cut. Is 0.5 correct?

I think we should all make an effort to put in the configuration files in xAH- at least for the analysis-independent cuts like JVT - the recommended versions for the various cuts, and possibly a few lines of comment and explaination (see [electronSelect*.config](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/data/electronSelect_signal.config) as an example )

Ciao

Marco

**Comment by jdandoy** [comment]
Hi Marco,

Those values are for the JVF cut, not the JVT cut.  The JVT cut values are
below, and the nominal is 0.64.  The recommendations can be found here:

https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/JetVertexTaggerTool

Rather than put the values in the config it may be more useful to put a
link to the twiki.  If people want to use other recommendations they should
probably check what goes into the values and why.  For example, the twiki
states that alternative values are "made available for testing in case
topology dependences such as those observed in 2012 data".

Jeff

**Comment by kratsg** [comment]
@jdandoy -- you could add a link here: https://github.com/UCATLAS/xAODAnaHelpers/wiki/Tools-Used

**Comment by mmilesi** [comment]
My bad, yesterday night I must have been very tired and the JVF/JVT thing blurred out... all good then!
Sorry for the noise, closing this.
