### ISSUE TITLE
Compilation crash for m_SmoothedWZTagger_handle

### ISSUE THREAD

**Issue by akilgall** [UCATLAS/xAODAnaHelpers#1373]
Hello,

I am unable to compile xAODAnaHelpers, and I'm a little unsure why, as I feel like this has always worked before for me.  Here's the error code:

[ 64%] Building CXX object xAODAnaHelpers/CMakeFiles/xAODAnaHelpersLib.dir/Root/L1JetContainer.cxx.o
/afs/cern.ch/user/a/aakilgal/lowmuSampleNtupleMaker4/LowMuZSearch/src/xAODAnaHelpers/Root/JetCalibrator.cxx: In member function 'virtual EL::StatusCode JetCalibrator::execute()':
/afs/cern.ch/user/a/aakilgal/lowmuSampleNtupleMaker4/LowMuZSearch/src/xAODAnaHelpers/Root/JetCalibrator.cxx:473:29  error: 'class SmoothedWZTagger' has no member named 'decorateTruthLabel'
  m_SmoothedWZTagger_handle->decorateTruthLabel(*jet_itr);

Here are the commands to reproduce this problem.

ssh -Y lxplus6.cern.ch
setupATLAS
mkdir workDir
cd workDir
mkdir src build
cd src
asetup AnalysisBase,21.2.65,here
git clone https://github.com/UCATLAS/xAODAnaHelpers
cd ../build
cmake ../src/
make

Cheers,

Aaron

**Comment by kratsg** [comment]
Hi @akilgall , the problem is the release you're setting up. As you can see in [release/21.2.65](https://gitlab.cern.ch/atlas/athena/blob/release/21.2.65/Reconstruction/Jet/BoostedJetTaggers/BoostedJetTaggers/JSSTaggerBase.h) -- the JSS tagger base doesn't have that function. This seems to have been added after `21.2.65` and exists in [newer releases](https://gitlab.cern.ch/atlas/athena/blob/21.2/Reconstruction%2FJet%2FBoostedJetTaggers%2FBoostedJetTaggers%2FJSSTaggerBase.h).

Note that the latest of xAH explicitly states in [documentation](https://xaodanahelpers.readthedocs.io/en/master/) at the very top that we need at least `21.2.90` here. If you want `21.2.65`, then you'll want an older version... but this feature was added in #1352 which requires at least `21.2.84`.

**Comment by akilgall** [comment]
Oh, I see.  I read the following on the documentation site and assumed I needed to do "asetup 21.2.65,here":

"We support the following releases: AnalysisBase,21.2.65, AnalysisTop,21.2.65, AnalysisBase,21.2.64, AnalysisTop,21.2.64, AnalysisBase,21.2.62, AnalysisTop,21.2.62, AnalysisBase,21.2.61, AnalysisTop,21.2.61,"

Thank you for the help!

**Comment by kratsg** [comment]
Can you refresh, it might be that you have a slight cache. I forced the docs to rebuild earlier today.
