### ISSUE TITLE
[Question]Truth labeling in the jet calibration tool

### ISSUE THREAD

**Issue by prbbing** [UCATLAS/xAODAnaHelpers#1601]
Dear Experts,

Could someone elaborate more on why these lines are needed:

https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/JetCalibrator.cxx#L405-L421

Reading the comments it looks like the jet systematic needs this. But it puzzles me that we need to decorate the jet.

Apologize if I have overlooked anything, and thanks for any insights.

Cheers.

Bing

**Comment by jbossios** [comment]
Hi @prbbing 

Indeed this is needed for applying some jet systematics. This is explained here: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JetUncertaintiesRel21Summer2018SmallR#Tool_requirements_and_assumption

Best,
Jona

**Comment by prbbing** [comment]
Hi @jbossios ,

Thanks. Apparently it was the twiki page overlooked...

If I understand correctly, here one needs to define the truth labeling. Does it matter much whether we use parton labeling or hadron labeling?

Cheers.

Bing

**Comment by jbossios** [comment]
For these (flavour and BJES) uncertainties, it should be based on PartonTruthLabelID, since that is what it is used to derive them. I'm not sure if anyone ever investigated the impact of using hadron labelling instead.

**Comment by jbossios** [comment]
I just add a note that PartonTruthLabelID should be used. Thanks for the suggestion.

**Comment by dguest** [comment]
Is there some reason the JetUncertainties tool doesn't check `PartonTruthLabelID` itself?

**Comment by jbossios** [comment]
This is for the old flavour uncertainties. For the consolidated recommendations, there were no flavour uncertianties for those jets flagged as b-jet by the user, for those, there was a dedicated bJES uncertainty.

For the new (per-jet) flavour uncertainties, the tool relies on PartonTruthLabelID directly and it supports g,u/d/s,c,b and the old bJES uncertainty is dropped.

**Comment by dguest** [comment]
I don't really have a good context for "old" or "new" here, what is going to be used in release 22? We should implement that, right @prbbing?

**Comment by jbossios** [comment]
The "old" [1] approach will be used for the R22 pre-recommendations, while the "new" approach [2] is expected to be used in the R22 consolidated recommendations.

xAH is ready for the R22 pre-recommendations.

Regarding, the "new" approach (i.e. the R22 consolidated recs), not even JetCalibTools is ready for that. Once all the tools are ready from the JetEtmiss side, we cherry-pick the following and we would be ready: https://github.com/UCATLAS/xAODAnaHelpers/pull/1560. At the moment, it was left out when porting xAH to R22 because it is not supported yet and I would say it is better not to add something that if used will crash.

[1] The one we had for many years where we have two components: flavour composition and flavour response. This is likely the one you are familiar with already.

[2] https://indico.cern.ch/event/1184001/contributions/4982958/attachments/2486386/4269253/Presentation.pdf and https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JetUncertaintiesRel21Summer2018SmallR#JES_Precision_Reduced_Flavour_Un
