### ISSUE TITLE
Problem with 'truth_details' output flag - Jet truth

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#181]
Hi @gfacini , @jdandoy 

I am trying to play around with jet truth, so I tried to run on a test file of a full mc15 xAOD:

mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.AOD.e3698_s2608_s2183_r6630_r6264

switching on the following flags in the tree configuration file:

```
1.  truth
2.  truth_details
```

However, activating `truth_details ` leads to a crash at run time:

```
terminate called after throwing an instance of 'SG::ExcAuxTypeMismatch'
  what():  SG::ExcAuxTypeMismatch: Type mismatch for aux variable `::GhostPartons' (257); old type is std::vector<ElementLink<DataVector<xAOD::IParticle, DataModel_detail::NoBase> >, std::allocator<ElementLink<DataVector<xAOD::IParticle, DataModel_detail::NoBase> > > > new type is std::vector<xAOD::TruthParticle_v1 const*, std::allocator<xAOD::TruthParticle_v1 const*> >
Aborted
```

Have you already noticed that happening?

Please let me know if you need additional info.

Also, it'd be great to have some concise documentation on the meaning of the various truth branches. 

Thanks,
Marco

**Comment by kratsg** [comment]
You need to retrieve it as an IParticle and not a TruthParticle. Where is this crashing?

**Comment by mmilesi** [comment]
Hi @kratsg ,

I don't know, since I did not take care of that part of the code. Guess in `HelpTreeBase::FillJets()`, but I'd wait for @jdandoy and @gfacini to chime in....

**Comment by jdandoy** [comment]
Looks like an obvious type mismatch at https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L1731.  Looks like it was changed from https://github.com/UCATLAS/xAODAnaHelpers/commit/34da1570229f3fbdb5c96381f07ae2787aab7655#diff-536048c8c92cb3373780d12a4b75a621L831

and is listed as a TruthParticle https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/Run2JetMoments#Jet_associations , though it obviously isn't in this file.  

We're overloaded this week due to the approval of several early EPS results, how pressing is this issue?

**Comment by gfacini** [comment]
Hi Marco,
Looks like you found the answer to your other questions
about the truth association ;-)
The complete list is here:
https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/Run2JetMoments
We have not used the "details" part since it was introduced.
If you need it quickly, I suggest making the change directly.
Cheers,
Gabriel
