### ISSUE TITLE
Which jet eta attribute in JVT cut?

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#196]
Hi jet-people :rocket: 

I am doing an acceptance challenge of the FW with other guys in HTop, and we have perfect agreement :blush:, except for the jet counting after the JVT cut.

I dug into the code and I found that the difference is in the way they retrieve the jet eta: they do simply:

```
if ( fabs( jet->eta() ) < eta_cut ) { ... }
```

whereas in our JetSelector.cxx I see this:

```
xAOD::JetFourMom_t jetScaleP4 = jet->getAttribute< xAOD::JetFourMom_t >( m_jetScaleType.c_str());
 if ( fabs(jetScaleP4.eta()) < m_eta_max_JVT ){ ... }
```

Given I am using `Anikt4EMTopo` jets, the jet scale for me would be `m_jetScaleType = "JetEMScaleMomentum"`, which makes quite sense.

Looks like ` jet->eta()` returns another attribute, but then which one is the correct one?
I see that for the | eta | cut we still use `jet->eta()`. Where is the recommendation on which eta to be used? I cannot find any info in the JetEtMiss Twikis.

For your record, this is the cutflow spreadsheet:

https://docs.google.com/spreadsheets/d/1zUfJ6hsv-ro0GOHdR5qJYuR9ss4kTcqojJWJ965MbLY/edit#gid=1328971955

Thanks for your help.

Marco

@jdandoy @johnda102 @gfacini @kratsg @fizisist

**Comment by kratsg** [comment]
Hi @mmilesi, so our way is actually closer to being more flexible and correct since we provide access to multiple states. It is slightly outdated since there is an actual function that does this part for you now, but...

http://acode-browser.usatlas.bnl.gov/lxr/source/atlas/Event/xAOD/xAODJet/Root/Jet_v1.cxx#0193

The default state in jets is usually `JetAssignedScaleMomentum`. This is what is set by the `momentumAcc` which you see here: http://acode-browser.usatlas.bnl.gov/lxr/source/atlas/Event/xAOD/xAODJet/Root/Jet_v1.cxx#0087

@fizisist and @mswiatlo can comment specifically on the details of the states (or what differentiates them) as they know more than I do specifically.

The code for

```c++
xAOD::JetFourMom_t jetScaleP4 = jet->getAttribute< xAOD::JetFourMom_t >( m_jetScaleType.c_str());
 if ( fabs(jetScaleP4.eta()) < m_eta_max_JVT ){ ... }
```

can and should be equivalently written as

```c++
if( fabs(jet->jetP4(m_jetScaleType).eta()) < m_eta_max_JVT ){ ... }
```

which is a little clearer (someone should make a commit to change the code and refer to #196).

Note that all Jet Scales are defined here: http://acode-browser.usatlas.bnl.gov/lxr/source/atlas/Event/xAOD/xAODJet/xAODJet/JetTypes.h

**Comment by jdandoy** [comment]
Hi Marco,

I agree from the JVT documentation that it's not obvious which one to
use.   The one we use in xAODAnaHelpers is the const/EM scale eta (detector
eta), and it the eta of the jet measured with respect to the center of the
detector.  The final jet->eta() includes an origin correction which changes
the eta of the jet to point to the location of the primary vertex.  Overall
the shift should be small (Looks like a .04% difference in this case).
Many calibrations prefer to use the detector eta, though this may be a
place to use the corrected eta.  It all depends on which eta definition was
used by the developer of the tool when the working points were defined.  If
Gabriel and David agree then I think we can switch to using the calibrated
jet->eta().

Jeff

**Comment by gfacini** [comment]
Hello!

What we have now is correct - detector eta.
We should not switch to eta.

The motivation for 2.4 is that the jet is within
the acceptance of the tracking detector.  This
has been the recommendation from JetETMiss
for JVF and should carry on here since the
same concern is valid.

A study was done a long time ago showing that
the JVF efficiency drops between 2.4 and 2.5
since a significant fraction of the jet it outside of
the tracking acceptance.

Marco, educate your collaborators =)

Cheers,
Gabriel

**Comment by mmilesi** [comment]
Hi guys, thanks for your replies!

@gfacini : however, I don't get the connection between your bullet 1 (first paragraph) to the following two paragraphs. I understand instead @jdandoy 's point regarding the eta definition for which the WP were derived.

Marco

**Comment by gfacini** [comment]
What was not clear?

I hope the point was clear that we should *not*
use the calibrated eta.

The tracker has limited coverage and the JVT
(which is built using JVF) uses tracks.

Also the acceptance of the tracker is 2.5 in eta.
Jets have a width, so a jet with eta = 2.5 is only
1/2 inside the tracking coverage. Thus the cut is
2.4 and that is a detector quantity not a physics
quantity.

Gabriel

**Comment by mmilesi** [comment]
:+1: :ok_hand:

**Comment by gfacini** [comment]
=)
