### ISSUE TITLE
"_Insitu" is appended when running on data

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#348]
Hello

I would like to use this framework to derive the insitu correction for the Rscan but when I run on data "_Insitu" is added to the calibration sequence even when I don't specify that. Since there is no insitu yet for the Rscan, JetCalibTools crash. Is it possible to change this? I'm using xAODAnaHelpers-00-03-25. For the moment I will just comment that part.

Cheers,
Jona

**Comment by gfacini** [comment]
Hi Jona,

I think adding this as default is probably the
behavior we want. Since your work is for
development only, I would suggest making
a patch that you apply when you check out
the package.

The logic is that when you are done with the
project, you will not want to turn off the in situ
corrections again for data, would you?

https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

Cheers,
Gabriel

**Comment by jbossios** [comment]
Hi Gabriel

That sounds good enough to me. I can imagine more people needing this if they want to use this framework for performance studies. This can be used too by people who wants to start looking into AntiKt4LCTopoJets which don't have insitu correction yet.

Cheers,
Jona

**Comment by gfacini** [comment]
Hi Jona,

If it would be useful, then you can always add the
configuration switch as long as

1. the default behavior does not change
2. it dumps tons of warnings when turned on
since this is "expert only" stuff.


Cheers,
Gabriel
