### ISSUE TITLE
HelpTreeBase: Branches created without asking for them

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#484]
Hi

I recently changed from xAODAnaHelpers-00-03-25 to xAODAnaHelpers-00-03-29. I'm using Base,2.3.39 and HelpTreeBase to create a tree. Now I'm having some tree files with TileError, SCTError and LArError and some others without those branches using the same code. Event when I don't ask for them. I turned on m_debug and as you can see I'm not requesting them:

AddEvent()                INFO    Adding event variables: pileup shapeEM

I don't know what can be the problem. Any idea?

Cheers,
Jona

**Comment by urania277** [comment]
Hi Jona,

I added the *Error branches, looking into it.

Caterina

**Comment by urania277** [comment]
Hi Jona,

I suspect that 00-03-29 is affected by #451 , which means that the switch for those branches was not initialized properly. The fix is easy though and you can do it locally + recompiling if you don't want to change versions, just add this line: 

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelperClasses.cxx#L87

Let me know if this works, and sorry about that!

Caterina

**Comment by jbossios** [comment]
Hi Caterina

Thank you very much! I will try with that.

Cheers,
Jona

**Comment by kratsg** [comment]
Hi @jbossios -- looking at the code, you can find the relevant commit that @urania277 made to fix it -- https://github.com/UCATLAS/xAODAnaHelpers/commit/d3694ed0b26aad71c42422a59327f88b9bd0df18

which is associated with 00-03-30 and AB2.3.41 . Maybe you can try that at the latest.

**Comment by kratsg** [comment]
If there's no other problems, @jbossios , I will close this.
