### ISSUE TITLE
BasicEventSelection and CutBookkeepers when running directly on xAODs

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#504]
We are in the process of finalizing the derivation for the dijet+ISR analysis, so in the meantime I've been running directly on xAODs. But `BasicEventSelection` only uses the `CutBookkeepers` to get the intial `sumOfWeights` if you are running on a derivation. See the check at https://github.com/UCATLAS/xAODAnaHelpers/blob/059735b/Root/BasicEventSelection.cxx#L213 .

My questions:
1. Is there a reason why `BasicEventSelection` is restricted to DxAODs only?
2. Why do we care about the `CutBookkeeper` associated with the derivation? I don't see it being use for anything other than printing out a number (verbosity?).

Also I don't think the "non meta-data" implementation of this is correct. It takes the first event weight and multiplies it by the number of entries. I don't think this works if events have different weights.
`m_MD_initialSumW        = CollectionTree->GetWeight() * CollectionTree->GetEntries()`

**Comment by mmilesi** [comment]
Hi @kkrizka ,

> 1. Is there a reason why BasicEventSelection is restricted to DxAODs only?

AFAIK, only derivations apply event cuts from the primary xAOD, so it's in the derivations that one wants to keep track of the original number of generated events to get the correct normalisation. For a full xAOD, this problem does not exist, hence it skips till https://github.com/UCATLAS/xAODAnaHelpers/blob/059735b/Root/BasicEventSelection.cxx#L288

> 2. Why do we care about the CutBookkeeper associated with the derivation? I don't see it being use for anything other than printing out a number (verbosity?).

You mean https://github.com/UCATLAS/xAODAnaHelpers/blob/059735b/Root/BasicEventSelection.cxx#L257 ?
Well, that is actually used to get https://github.com/UCATLAS/xAODAnaHelpers/blob/059735b/Root/BasicEventSelection.cxx#L277 etc., and finally to fill the metadata histogram https://github.com/UCATLAS/xAODAnaHelpers/blob/059735b/Root/BasicEventSelection.cxx#L167

> Also I don't think the "non meta-data" implementation of this is correct. It takes the first event weight and multiplies it by the number of entries. I don't think this works if events have different weights.
> m_MD_initialSumW = CollectionTree->GetWeight() * CollectionTree->GetEntries()

Mmmh, yes I think you are right on this, I didn't think about generators with different mcEventWeights (e.g., Sherpa) when I originally implemented it, then it went unnoticed since most of us have been using derivations all the time. I can rather get also those numbers from the CutBookkeepers. I will fix this now, and file a PR. Thanks for spotting it!

**Comment by mmilesi** [comment]
PR #507
