### ISSUE TITLE
metadata histogram no longer filled if m_useMetaData false

### ISSUE THREAD

**Issue by lawrenceleejr** [UCATLAS/xAODAnaHelpers#533]
Hi @mmilesi,

Why did #507 cause the metadata histogram to not be filled unless m_useMetaData is true? Previous to this, it seems that the histogram was filled no matter what from different sources. Is it planned to get this behavior back? (I can see that you're actively playing with it.)

Thanks!
-Larry

**Comment by kratsg** [comment]
@kkrizka -- can you look at this too?

**Comment by kkrizka** [comment]
I believe the correct way to (re)implement this is by filling the metadata histogram at the beginning of `execute()` for each event. This is only when `m_useMetaData=false`.

I can look at it now.

**Comment by mmilesi** [comment]
Hi Larry!

I made that change after Karol pointed out that a few derivations remove completely the CutBookkeepers container, hence leading to crash.

For that samples, so far the way to get the correct normalisation weight is to read it from the cutflow, which is filled event per event. This is correct of course only under the assumption that the DAOD hasn't been skimmed from the original AOD. In that case, people should report to the DF team to make sure  CutBookkeepers is always stored.

**Comment by kratsg** [comment]
@mmilesi -- if I understand correctly: is this a derivation-specific issue? Which derivations does this _not_ break on for example? How do we know?

**Comment by mmilesi** [comment]
Hi Giordon,

I guess that all the derivations used by "standard" physics analyses keep the CutBookkeeepers container. Karol found that TRUTH1 derivations do not store it though.

The way I implemented it leaves up to the user the possibility to skip the CutBookkeepers reading part, depending on the input samples used. I cannot think about a nice way to instruct xAH on the existence of CutBookkeepers in the input files rather than using a `try...catch` block. Imho, the best is to let the user try, and if it crashes b/c of missing CutBookkeepers, just switch them off with `m_useMetadata=false`.

**Comment by kratsg** [comment]
> The way I implemented it leaves up to the user the possibility to skip the CutBookkeepers reading part, depending on the input samples used. I cannot think about a nice way to instruct xAH on the existence of CutBookkeepers in the input files rather than using a try...catch block. Imho, the best is to let the user try, and if it crashes b/c of missing CutBookkeepers, just switch them off with m_useMetadata=false.

Can you not check if it exists (i.e. null pointer?) before trying to use it? I can't imagine that, but I understand the reasoning here. It seems rather unfortunate that this is the case though. Can we use metadata *without* cutbookkeepers?

**Comment by mmilesi** [comment]
Yes, in case `m_useMetadata=false` we could fill `m_histEventCount` in `EL::execute()` using `mcEventWeight`. I think this is what @kkrizka  had in mind
