### ISSUE TITLE
Jet eta and JVT cut

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#553]
On the JVT TWiki:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JVTCalibration

it is said people should now use the jet "detector" eta (i.e, the one accessed via `jet->eta()`) rather than the "EMScale" eta for the JVT cut.

Trying to just keep the code structure we have now:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L669

does anyone know what  string should be assigned to `m_jetScaleType` , if any?

Marco

**Comment by mswiatlo** [comment]
“JetConstitScaleMomentum” will give you the detector-level 4-momentum.

Cheers,
Max


On Mar 22, 2016, at 5:27 AM, Marco Milesi <notifications@github.com<mailto:notifications@github.com>> wrote:


On the JVT TWiki:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JVTCalibration

it is said people should now use the jet "detector" eta (i.e, the one accessed via jet->eta()) rather than the "EMScale" eta for the JVT cut.

Trying to just keep the code structure we have now:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L669

does anyone know what string should be assigned to m_jetScaleType , if any?

Marco

**Comment by mmilesi** [comment]
Thanks! Can close this.
