### ISSUE TITLE
2.3.38 -> 2.3.45: 10x slower? 

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#572]
Hi all,

I've just moved forward to get all the good things from #566 and 2.3.45, but the downsides are that the same config now runs 10x slower (and I haven't yet turned on the systematics). Ntuplizing 10k MC events take 200 seconds vs 20 seconds from my latest PR around mid-February, when I was on 2.3.38. The snapshot is here: https://github.com/urania277/xAODAnaHelpers

Admittedly, I haven't really followed everything too closely, but I didn't think anything major would have changed to my private tree-dumping code downstream except for this systematic change. 

Has anyone else noticed this / am I doing something wrong / do you have any ideas on where to start looking for reasons for this speed-down?

Thanks,
Caterina

**Comment by kratsg** [comment]
Hi @urania277 -- This sounds really bad. For anyone reading this -- comparison is here: https://github.com/UCATLAS/xAODAnaHelpers/compare/5a93d3...master so I wonder what got screwed up.

In fact, looking here: https://github.com/UCATLAS/xAODAnaHelpers/compare/5a93d3...master#diff-536048c8c92cb3373780d12a4b75a621 (at HelpTreeBase) shows that nothing changed drastically for the ntuplizing of the inputs. So I wonder if the slow down is due to the AnalysisBase release changes instead of our code changes?

**Comment by mmilesi** [comment]
Has anyone tried to run xAH with BasicEventSelector only in 2.3.39 VS 2.3.45?

**Comment by urania277** [comment]
No change in time for me there (ran on the same file, .38 vs .45). Will try a test w/ntuple too.

**Comment by urania277** [comment]
Ok, I've tried with the same exact configuration and same file in the two releases and the speed-down is not dramatic (30 seconds over ~5 minutes for 10k events). Possibly there's nothing to worry about...sorry to have made you concerned! The up-side of this testing is that the systematics in #566 work well :)

**Comment by mmilesi** [comment]
:beers:
