### ISSUE TITLE
Handle single root files as input

### ISSUE THREAD

**Issue by AvivCukierman** [UCATLAS/xAODAnaHelpers#778]
Currently ```--files root://sample.root``` doesn't work. For quick testing it might be nice if it did.

**Comment by kratsg** [comment]
I'm just seeing this, sorry! This is supported in two different ways. Way 1: if you run `xrdcp root://sample.root sample.root` and then run `xAH_run.py --files sample.root` -- this is fine. The other way is to use `scanXRD` which scans the XRD server for you to add it. There's no other way to support this because SampleHandler doesn't support it, unfortunately.
