### ISSUE TITLE
making subset containers

### ISSUE THREAD

**Issue by fscutti** [UCATLAS/xAODAnaHelpers#838]
Hi @mmilesi, @kratsg, @jdandoy, 
when performing the OR, the function HelperFunctions::makeSubsetCont is used to create a container pointing at the objects passing the OR. The syst output containers created in this way may be just be a subset in memory of the nominal one. I find this to be a problem when decorating objects downstream e.g. with reco efficiencies. For instance, one of these containers could be muons_OR+ele_calibration_sys. Now, while these objects should be saved in a different tree than nominal, when decorating them with efficiencies, also the nominal ones will receive the decoration, which should obviously be written in the nominal tree. 

I believe the solution to this would be to change the memory location of the objects in the OR output container, hence, changing a bit the HelperFunctions::makeSubsetCont, but I am unsure if this would be the best thing to do. What do you guys think?

**Comment by kratsg** [comment]
Hi @fscutti the proper procedure is as follows.

- To make a subset of a container without modification, use a ConstDataVector that is VIEW_ONLY and does not manage the memory.
- To make modifications to an existing container without changing what elements are in it, you make a shallow copy and make modifications on the shallow copies.
- To make modifications to a subset of an existing container, you must make deep copies. This is because you have to change the order of the elements as well as making a non-read-only copy which you modify.

In the downstream algorithms, they should know what they want to do and either make a deep copy, a shallow copy, or a CDV. In your case, use the makeSubsetCont and then [makeDeepCopy](http://xaodanahelpers.readthedocs.io/en/master/HelperFunctions.html?highlight=makeDeepCopy#_CPPv2N15HelperFunctions12makeDeepCopyEPN4xAOD6TStoreENSt6stringEPK2T1) function in the HelperFunctions -- and that gets you the memory you need. The CDV contains only the elements you want to modify, then a deep copy of those elements into a new container which is recorded to the TStore (for memory management) does the trick.

[See the documentation here](http://xaodanahelpers.readthedocs.io/en/master/HelperFunctions.html?highlight=makeDeepCopy#_CPPv2N15HelperFunctions12makeDeepCopyEPN4xAOD6TStoreENSt6stringEPK2T1) for more information.

**Comment by fscutti** [comment]
Hi @kratsg, 
thank you for your answer. Could you please review my pull request?
