### ISSUE TITLE
Document changes to Efficiency Correctors and running multiple times

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#853]
See the discussion raised in #839.

**Comment by fscutti** [comment]
Hi,
I have problems following the instructions [here](http://xaodanahelpers.readthedocs.io/en/latest/HowToDocumentation.html?highlight=documentation) to generate documentation, due to troubles installing sphinx or with its version which I cannot change. Is there a more straightforward way to generate documentation?

**Comment by kratsg** [comment]
Which step are you having a problem with? Doxygen generates documentation, and Sphinx formats it into an html page. Both are very widespead.

**Comment by fscutti** [comment]
If I try to follow these steps

cd docs
make clean
doxygen
make html
open _build/html/index.html

when I try to generate the html I get on the Melbourne cloud 
`sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v0.6.6

`Exception occurred:
  File "/imports/home/fscutti/xAODAnaHelpers/docs/conf.py", line 83, in <module>
    import yaml
ImportError: No module named yaml
The full traceback has been saved in /scratch/sphinx-err-iMYne7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

I did not play too much with this but might be related with the sphinx version. Any idea?

**Comment by kratsg** [comment]
It's not related to the sphinx version. Did you run the `pip install -r requirements.txt`? It includes a line that installs yaml for you: https://github.com/UCATLAS/xAODAnaHelpers/blob/master/docs/requirements.txt#L4

**Comment by fscutti** [comment]
This is the other problem. On my local machine this generates an error this is why I was trying to do it on the Melbourne cloud. But to install something I might need to contact the admin. I'll check with them.

**Comment by kratsg** [comment]
This is why I suggested using virtual environments. You can install an entire set of python packages locally without installing it everywhere. Virtual environments work this way. What error are you getting?

**Comment by fscutti** [comment]
When I execute pip install -r requirements.txt I get the error at [this link](https://www.dropbox.com/s/a5faojgzww6lrx0/error.txt?dl=0). It seems indeed unrelated to sphinx.

**Comment by kratsg** [comment]
You're not in a virtual environment. This is installing it globally. You want to install this locally to make sure you have no conflicts. Did you install your virtual environments?

**Comment by fscutti** [comment]
If I pip install virtualenvwrapper
I get [this error](https://www.dropbox.com/s/eio5qjm4g0o6edg/error2.txt?dl=0)

**Comment by kratsg** [comment]
Yes, you need to install virtualenvwrapper locally. `pip install --user virtualenvwrapper`.

**Comment by fscutti** [comment]
Ok thanks this seems to work. So after the installation I have now created a .bashrc file with 

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/xAODAnaHelpers
source /Users/fscutti/Library/Python/2.7/bin/virtualenvwrapper.sh

After sourcing it,  when I try to make a virtual environment, e.g. mkvirtualenv xAH I get

ERROR: virtualenvwrapper could not find virtualenv in your path

There has to be something obvious I am missing here.

**Comment by kratsg** [comment]
http://stackoverflow.com/questions/31274642/error-virtualenvwrapper-could-not-find-virtualenv-in-your-path

**Comment by kratsg** [comment]
Any updates on this? ping me on skype or gchat (@kratsg or kratsg@gmail) if you need to debug still.

**Comment by fscutti** [comment]
Hi @kratsg, all is resolved now. I'm just very busy now. And when I'm not busy I'm lazy. I'll do that tomorrow.
