### ISSUE TITLE
Broken JetCalibrator for 2.4

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#946]
It seems that https://github.com/UCATLAS/xAODAnaHelpers/pull/928/commits/33572d9a2f02da29cba829436b78199a937b62e5 broke the JetCalibrator for 2.4. Commenting out the changes fixes running it. Should this be 2.6/21.0 specific?

(Also this doesn't seem to be photon specific, but was merged in the same PR. Maybe not a good idea 😊)

**Comment by kratsg** [comment]
@jdandoy can you please look at this? Thanks!

**Comment by jdandoy** [comment]
Hi @ntadej,

Can you say specifically how things are broken for you?  I'm guessing it's because the recommended AB version is out of date, as this necessary feature for release 21 was only introduced for 2.6.3 and 2.4.32 (we're listed as 2.6.2 and 2.4.31).  

See #928, the name of the JVT decoration is different in Release 21 and Release 20.7, and the official tool (and therefore our tool) was updated to allow this name to be set in the config file (as detailed in the comment above the variable [here](https://github.com/UCATLAS/xAODAnaHelpers/blob/33572d9a2f02da29cba829436b78199a937b62e5/xAODAnaHelpers/JetCalibrator.h#L106).  As we don't have a way for the algorithms to know generally if you're running on 20.7 or 21, you will need to set this in your config file if you're using 20.7.  The default value is set for release 21.

**Comment by ntadej** [comment]
The issue is that `JVFCorrName` property doesn't even exist in 2.4.31 or 2.4.32. I set the 20.7 version of the decoration and it didn't help.

**Comment by jdandoy** [comment]
Okay, it seems that [JetMomentTools-00-03-62](https://svnweb.cern.ch/trac/atlasoff/browser/Reconstruction/Jet/JetMomentTools/tags/JetMomentTools-00-03-62/Root/JetVertexTaggerTool.cxx) is not actually available yet in any 2.4.X, and there doesn't seem to be a request for it.  I'll make a request, and update a patch for the checkout tags code.  In the meantime, please download JetMomentTools-00-03-62 manually and give it a try.

Jeff

**Comment by kratsg** [comment]
@jdandoy do you need a flag for rel21/rel20.7? Because as far as I'm aware, there is a way to check using the metadata in the file? Would this help?

**Comment by jdandoy** [comment]
Hi @kratsg,

It may help make things a bit more backwards compatible, as now people need to be aware and update their config file or else maybe get an error.  But that's true for all the release 21 calibrations, and people should be moving to release 21 anyway. 

I've asked for an update to 2.4.33 [on JIRA](https://its.cern.ch/jira/browse/ATLASG-1248).

**Comment by ntadej** [comment]
Thanks @jdandoy for the feedback. Until there are all samples and derivations available, I can not migrate to rel. 21 so I will use one of the workarounds for now.

**Comment by jdandoy** [comment]
Hi @ntadej,

That's understandable, please try out JetMomentTools-00-03-62 and let me know if it does or doesn't work with your RootCore setup.  I've just heard from Johannes that it shouldn't be compatible with 2.4.X, though I'm using it successfully myself.

**Comment by ntadej** [comment]
This was fixed using #948.
